export default {
  AXIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/axis_bank.svg",
  HDFB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/hdfc_bank.svg",
  ICIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/icici_bank.svg",
  ktk_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/kotak_bank.svg",
  SBIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/sbi_bank.svg",
  UBIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/union_bank.svg",
  ALLA_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/allahabad_bank.svg",
  ADBB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/andhra_bank.svg",
  BBKM_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/bankof_bahrain.svg",
  BARB_C_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/bankof_baroda.svg",
  BARB_R_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/bankof_baroda.svg",
  BOIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/bank_of_india.svg",
  BOMB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/bank_of_maharashtra.svg",
  CABB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/canara_bank.svg",
  CSBN_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/catholic_syrian_bank.svg",
  CBIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/central_bank_of_india.svg",
  CUBB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/city_union_bank.svg",
  CRPB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/corporation_bank.svg",
  CSMSNB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/cosmos_co_operative.svg",
  DBSS_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/dbs_bank.svg",
  DCBCORP_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/dcb_bank_corporate.svg",
  BKDN_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/dena_bank.svg",
  DSHB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/deutsche_bank.svg",
  DCBB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/development.svg",
  DLXB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/dhanalakshmi_bank.svg",
  FEDB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/federal_bank.svg",
  IDBB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/idbi_bank.svg",
  IDFB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/idfc_bank.svg",
  INDB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/indian_bank.svg",
  INOB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/indian_overseas.svg",
  INIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/indusInd_bank.svg",
  JAKB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/jammu_kashmir_bank.svg",
  JSBNB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/janata_sahakari.png",
  KRKB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/karnataka_bank.svg",
  KRVBC_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/karur_vysya_bank.svg",
  KRVB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/karur_vysya_bank.svg",
  LVCB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/lakshmi_vilas_bank.svg",
  LVRB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/lakshmi_vilas_bank.svg",
  OBCB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/oriental_bank.svg",
  PMNB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/punjab_maharashtra.svg",
  PSBNB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/punjab_sind_bank.svg",
  CPNB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/punjab_national_bank.svg",
  PNBB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/punjab_national_bank.svg",
  RATN_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/ratnakar_bank.svg",
  SRSWT_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/saraswat_bank.svg",
  SVCNB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/shamrao_vithal.svg",
  SOIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/south_indian_bank.svg",
  SCBL_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/standard_chartered.svg",
  SBBJB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/sbi_bank.svg",
  SBHB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/sbi_bank.svg",
  SBMB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/sbi_bank.svg",
  SBPB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/sbi_bank.svg",
  SBTB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/sbi_bank.svg",
  SYNDB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/syndicate_bank.svg",
  TNSC_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/tamil_nadu_state_apex.png",
  TMBB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/tamilnad_mercantile.png",
  TBON_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/the_nainital_bank.png",
  UCOB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/uco_bank.svg",
  UBIBC_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/union_bank.svg",
  UBIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/union_bank.svg",
  UNIB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/union_bank.svg",
  VJYB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/vijaya_bank.svg",
  YESB_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/yes_bank.svg",
  /* bank icons start */
  /*moreBanks Code */
  AMEX_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/amex.svg",
  AXIS_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/axis_bank.svg",
  AXISD_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/axis_bank.svg",
  CITI_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/city_union_bank.svg",
  HDFC_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/hdfc_bank.svg",
  HSBC_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/hsbc_bank.svg",
  ICICI_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/icici_bank.svg",
  ICICID_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/icici_bank.svg",
  INDUS_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/indusInd_bank.svg",
  KOTAK_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/kotak_bank.svg",
  SBI_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/sbi_bank.svg",
  STND_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/standard_chartered.svg",
  YES_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/yes_bank.svg",
  RBL_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/ratnakar_bank.svg",
  BOB_Bank_ic:
    "http://akam.cdn.jdmagicbox.com/images/icontent/payment_getway/bankof_baroda.svg",
};
